smart_app/urls.py
from django.conf.urls import url
from django.urls import path
from smart_app import views

app_name = "smart_app"

urlpatterns = [
   path('home/', views.home, name='home'),
   path('musician_form/', views.musician_form, name='musician_form'),
   path('album_form/', views.album_form, name='album_form'),
   path('album_list/<int:artist_id>/', views.album_list, name='album_list'),
   path('edit_artist/<int:artist_id>/', views.edit_artist, name='edit_artist'),
   path('edit_album/<int:album_id>/', views.edit_album, name='edit_album'),
   path('delete_album/<int:album_id>/', views.delete_album, name='delete_album'),
]

smart_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('smart_app.urls')),
]

smart_app/models.py
from django.db import models

# Create your models here.
class Musician(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name  = models.CharField(max_length = 50)
    instrument = models.CharField(max_length = 50)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Album(models.Model):
    artist       = models.ForeignKey(Musician, on_delete = models.CASCADE)
    name         = models.CharField(max_length = 100)
    release_date = models.DateField()
    rating       = (
    (1,'Worst'),
    (2,'Bad'),
    (3,'Not bad'),
    (4,'Good'),
    (5,'Excellent'),
    )

    num_stars    = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name + ' ' + str(self.num_stars)

smart_app/forms.py
from django import forms
from django.core import validators
from smart_app import models

class MusicianForm(forms.ModelForm):
    class Meta:
        model  = models.Musician
        fields = '__all__'
class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget = forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model  = models.Album
        fields = '__all__'

smart_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from smart_app.models import Musician, Album
from smart_app import forms
from django.db.models import Avg

# Create your views here.
def home(request):
    musician_list = Musician.objects.order_by('first_name')
    diction = {'title':'home page', 'musician_list':musician_list}
    return render(request, 'smart_app/home.html', context=diction)

def album_list(request, artist_id):
    artist_info   = Musician.objects.get(pk=artist_id)
    album_list    = Album.objects.filter(artist=artist_id).order_by('name')
    artist_rating = Album.objects.filter(artist=artist_id).aggregate(Avg('num_stars'))

    diction = {'title':'list of album','artist_info':artist_info,'album_list':album_list,'artist_rating':artist_rating}
    return render(request, 'smart_app/album_list.html', context=diction)

def musician_form(request):
    m_form  = forms.MusicianForm()

    if request.method == 'POST':
        m_form = forms.MusicianForm(request.POST)

        if m_form.is_valid():
            m_form.save(commit=True)
            return home(request)

    diction = {'title':'add musician', 'm_form':m_form}
    return render(request, 'smart_app/musician_form.html', context=diction)

def album_form(request):
    l_form = forms.AlbumForm()

    if request.method == 'POST':
        l_form = forms.AlbumForm(request.POST)

        if l_form.is_valid():
            l_form.save(commit=True)
            return home(request)
    diction = {'title':'add album', 'l_form':l_form}
    return render(request, 'smart_app/album_form.html', context=diction)

def edit_artist(request, artist_id):
    artist_info   = Musician.objects.get(pk=artist_id)
    edit_form  = forms.MusicianForm(instance=artist_info)

    if request.method == 'POST':
        edit_form = forms.MusicianForm(request.POST, instance=artist_info)

        if edit_form.is_valid():
            edit_form.save(commit=True)
            return album_list(request, artist_id)


    diction = {'edit_form':edit_form,}
    return render(request, 'smart_app/edit_artist.html', context=diction)

def edit_album(request, album_id):
    album_info = Album.objects.get(pk=album_id)
    edit_form  = forms.AlbumForm(instance = album_info)
    diction = {}
    if request.method == 'POST':
        edit_form = forms.AlbumForm(request.POST, instance = album_info)

        if edit_form.is_valid():
            edit_form.save(commit=True)
            diction.update({'success_sms':'Successfully Updated'})


    diction.update({'edit_form':edit_form})
    diction.update({'album_id':album_id})
    return render(request, 'smart_app/edit_album.html', context=diction)

def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id).delete()
    diction = {'delete_sucess':'Successfully Deleted!'}
    return render(request, 'smart_app/delete.html', context=diction)

templates/smart_app/album_form.html
<!DOCTYPE html>
{% extends 'smart_app/base.html' %}
{% block body_block %}
<h3>Album Input Form</h3>
<form class="" action="" method="POST">
  {{ l_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
</form>
{% endblock %}

templates/smart_app/album_list.html
<!DOCTYPE html>
{% extends 'smart_app/base.html' %}
{% block body_block %}
<h4>Artist Name: {{ artist_info.first_name }} {{ artist_info.last_name }}</h4>
<h4>Instrument: {{ artist_info.instrument }}</h4>
<h4>Artist Rating: {{ artist_rating.num_stars__avg }}</h4>
<a href="{% url 'smart_app:edit_artist' artist_id=artist_info.id %}" class="btn btn-success btn-sm">Edit</a>
<h3>List Of Album</h3>
<table class="table table-bordered">
  <tr>
    <th>Artist Name</th>
    <th>Release Date</th>
    <th>Rating</th>
  </tr>
  {% for album in album_list %}
  <tr>
    <td> <a href="{% url 'smart_app:edit_album' album_id=album.id %}">{{ album.name }}</a> </td>
    <td>{{ album.release_date|date:"M d, Y" }}</td>
    <td>{{ album.num_stars }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

templates/smart_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <title>{{ title }}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
        <li class="nav-item active">
         <a class="nav-link" href="{% url 'smart_app:home' %}">Home</a>
        </li>
        <li class="nav-item">
         <a class="nav-link" href="{% url 'smart_app:musician_form' %}">Add Musician</a>
        </li>
        <li class="nav-item">
         <a class="nav-link" href="{% url 'smart_app:album_form' %}">Add Album</a>
        </li>
      </ul>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

templates/smart_app/delete.html
<!DOCTYPE html>
{% extends 'smart_app/base.html' %}
{% block body_block %}
 <h3 class="alert alert-danger">{{ delete_sucess }}</h3>
{% endblock %}

templates/smart_app/edit_album.html
{% extends 'smart_app/base.html' %}
{% block body_block %}
<h4>Edit Album</h4>
{% if success_sms %}
  <div class="alert alert-success">
    {{ success_sms }}
  </div>
{% endif %}
<form class="" action="" method="POST">
  {{ edit_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Update" class="btn btn-success btn-sm">
</form>
<br>
<a href="{% url 'smart_app:delete_album' album_id=album_id %}" class="btn btn-danger btn-sm" onclick="return confirm('Sure delete?')">Delete</a>
{% endblock %}

templates/smart_app/edit_artist.html
<!DOCTYPE html>
{% extends 'smart_app/base.html' %}
{% block body_block %}
<h4>Edit Artist</h4>
<form class="" action="" method="POST">
  {{ edit_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm">
</form>
{% endblock %}

templates/smart_app/home.html
<!DOCTYPE html>
{% extends 'smart_app/base.html' %}
{% block body_block %}
<h3>Home Page</h3>
<ul>
  {% if musician_list %}
  {% for musician in musician_list %}
    <li><a href="{% url 'smart_app:album_list' artist_id=musician.id %}">{{ musician.first_name }} {{ musician.last_name }}</a></li>
  {% endfor %}
  {% else %}
  <h4>No musician list</h4>
  {% endif %}
</ul>
{% endblock %}

templates/smart_app/musician_form.html
<!DOCTYPE html>
{% extends 'smart_app/base.html' %}
{% block body_block %}
<h3>Musician Form</h3>
<hr>
<form class="" action="" method="POST">
  {{ m_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
</form>
{% endblock %}